with source as (
  select * from {{ source('ar_raw', 'raw_hz_cust_accounts') }}
),

cleaned as (
  select
    cust_account_id,
    party_id,
    last_update_date::timestamp_ntz      as last_updated_at,
    account_number,
    last_updated_by,
    creation_date::timestamp_ntz         as created_at,
    created_by,
    last_update_login,
    orig_system_reference,
    status,
    customer_type,
    customer_class_code,
    primary_salesrep_id,
    sales_channel_code,
    order_type_id,
    price_list_id::number                 as price_list_id,
    subcategory_code,
    tax_code,
    fob_point,
    freight_term,
    ship_partial,
    ship_via,
    warehouse_id::number                  as warehouse_id,
    payment_term_id::number               as payment_term_id,
    tax_header_level_flag,
    tax_rounding_rule,
    coterminate_day_month,
    account_liable_flag,
    restriction_limit_amount::number      as restriction_limit_amount,
    current_balance::number               as current_balance,
    password_text,
    high_priority_indicator,
    account_established_date::timestamp_ntz as account_established_at,
    account_termination_date,
    account_activation_date::timestamp_ntz as account_activation_at,
    credit_classification_code,
    department,
    major_account_number,
    hotwatch_service_flag,
    hotwatch_svc_bal_ind,
    held_bill_expiration_date,
    hold_bill_flag,
    high_priority_remarks,
    po_effective_date,
    po_expiration_date,
    realtime_rate_flag,
    single_user_flag,
    watch_account_flag,
    watch_balance_indicator,
    geo_code,
    acct_life_cycle_status,
    account_name,
    deposit_refund_method,
    dormant_account_flag,
    npa_number,
    pin_number,
    suspension_date,
    write_off_adjustment_amount::number   as write_off_adjustment_amount,
    write_off_payment_amount::number      as write_off_payment_amount,
    write_off_amount::number              as write_off_amount,
    source_code,
    competitor_type,
    comments,
    dates_negative_tolerance,
    dates_positive_tolerance,
    date_type_preference,
    over_shipment_tolerance::number        as over_shipment_tolerance,
    under_shipment_tolerance::number       as under_shipment_tolerance,
    over_return_tolerance,
    under_return_tolerance,
    item_cross_ref_pref,
    ship_sets_include_lines_flag,
    arrivalsets_include_lines_flag,
    sched_date_push_flag,
    invoice_quantity_rule,
    pricing_event,
    account_replication_key::number       as account_replication_key,
    status_update_date,
    autopay_flag,
    notify_flag,
    last_batch_id,
    org_id,
    selling_party_id,
    federal_entity_type,
    trading_partner_agency_id,
    duns_extension,
    advance_payment_indicator,
    cancel_unshipped_lines_flag,
    rnum::number                          as rnum
  from source
)

select * from cleaned
