with source as (
  select * from {{ source('ar_raw', 'raw_ar_payment_schedules_all') }}
),

cleaned as (
  select
    payment_schedule_id,
    last_update_date::timestamp_ntz      as last_updated_at,
    last_updated_by,
    creation_date::timestamp_ntz         as created_at,
    created_by,
    last_update_login,
    due_date::date                       as due_date,
    amount_due_original::number          as amount_due_original,
    amount_due_remaining::number         as amount_due_remaining,
    number_of_due_dates,
    status,
    invoice_currency_code,
    class,
    cust_trx_type_id,
    customer_id,
    customer_site_use_id,
    customer_trx_id,
    cash_receipt_id,
    associated_cash_receipt_id,
    term_id,
    terms_sequence_number,
    gl_date_closed::date                 as gl_date_closed,
    actual_date_closed::date             as actual_date_closed,
    discount_date::date                  as discount_date,
    amount_line_items_original::number   as amount_line_items_original,
    amount_line_items_remaining::number  as amount_line_items_remaining,
    amount_applied::number               as amount_applied,
    amount_adjusted::number              as amount_adjusted,
    amount_in_dispute::number            as amount_in_dispute,
    amount_credited::number              as amount_credited,
    receivables_charges_charged::number as receivables_charges_charged,
    receivables_charges_remaining::number as receivables_charges_remaining,
    freight_original::number             as freight_original,
    freight_remaining::number            as freight_remaining,
    tax_original::number                 as tax_original,
    tax_remaining::number                as tax_remaining,
    discount_original::number            as discount_original,
    discount_remaining::number           as discount_remaining,
    discount_taken_earned::number        as discount_taken_earned,
    discount_taken_unearned::number      as discount_taken_unearned,
    in_collection,
    cash_applied_id_last,
    cash_applied_date_last::timestamp_ntz as cash_applied_last_at,
    cash_applied_amount_last::number      as cash_applied_amount_last,
    cash_applied_status_last,
    cash_gl_date_last::date              as cash_gl_date_last,
    cash_receipt_id_last,
    cash_receipt_date_last::date         as cash_receipt_date_last,
    cash_receipt_amount_last::number     as cash_receipt_amount_last,
    cash_receipt_status_last,
    exchange_rate_type,
    exchange_date::date                  as exchange_date,
    exchange_rate::number                as exchange_rate,
    adjustment_id_last,
    adjustment_date_last::date           as adjustment_date_last,
    adjustment_gl_date_last::date        as adjustment_gl_date_last,
    adjustment_amount_last::number       as adjustment_amount_last,
    follow_up_date_last::date            as follow_up_date_last,
    follow_up_code_last,
    promise_date_last::date              as promise_date_last,
    promise_amount_last::number          as promise_amount_last,
    collector_last,
    call_date_last::date                 as call_date_last,
    trx_number,
    trx_date::date                       as trx_date,
    attribute_category,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    reversed_cash_receipt_id,
    amount_adjusted_pending::number      as amount_adjusted_pending,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    gl_date::date                        as gl_date,
    acctd_amount_due_remaining::number   as acctd_amount_due_remaining,
    program_application_id,
    program_id,
    program_update_date::timestamp_ntz   as program_updated_at,
    receipt_confirmed_flag,
    request_id,
    selected_for_receipt_batch_id,
    last_charge_date::date               as last_charge_date,
    second_last_charge_date::date        as second_last_charge_date,
    dispute_date::date                   as dispute_date,
    org_id,
    staged_dunning_level,
    dunning_level_override_date::date    as dunning_override_date,
    global_attribute1,
    global_attribute2,
    global_attribute3,
    global_attribute4,
    global_attribute5,
    global_attribute6,
    global_attribute7,
    global_attribute8,
    global_attribute9,
    global_attribute10,
    global_attribute11,
    global_attribute12,
    global_attribute13,
    global_attribute14,
    global_attribute15,
    global_attribute16,
    global_attribute17,
    global_attribute18,
    global_attribute19,
    global_attribute20,
    global_attribute_category,
    cons_inv_id,
    cons_inv_id_rev,
    exclude_from_dunning_flag,
    mrc_customer_trx_id,
    mrc_exchange_rate_type,
    mrc_exchange_date,
    mrc_exchange_rate,
    mrc_acctd_amount_due_remaining,
    br_amount_assigned::number           as br_amount_assigned,
    reserved_type,
    reserved_value,
    active_claim_flag,
    exclude_from_cons_bill_flag,
    payment_approval
  from source
)

select * from cleaned
