
with source as (
  select * from {{ source('ar_raw', 'raw_ar_receivable_applications_all') }}
),

cleaned as (
  select
    receivable_application_id,
    last_updated_by,
    last_update_date::timestamp_ntz       as last_updated_at,
    created_by,
    creation_date::timestamp_ntz          as created_at,
    amount_applied::number                as amount_applied,
    gl_date::timestamp_ntz                as gl_date,
    code_combination_id,
    set_of_books_id,
    display,
    apply_date::timestamp_ntz             as apply_date,
    application_type,
    status,
    payment_schedule_id,
    last_update_login::number             as last_update_login,
    cash_receipt_id::number               as cash_receipt_id,
    applied_customer_trx_id::number       as applied_customer_trx_id,
    applied_customer_trx_line_id,
    applied_payment_schedule_id::number   as applied_payment_schedule_id,
    customer_trx_id::number               as customer_trx_id,
    line_applied::number                   as line_applied,
    tax_applied::number                    as tax_applied,
    freight_applied::number                as freight_applied,
    receivables_charges_applied::number   as charges_applied,
    on_account_customer,
    receivables_trx_id,
    earned_discount_taken::number         as earned_discount_taken,
    unearned_discount_taken::number       as unearned_discount_taken,
    days_late::number                      as days_late,
    application_rule,
    gl_posted_date::timestamp_ntz         as gl_posted_at,
    comments,
    postable,
    posting_control_id,
    acctd_amount_applied_from::number     as acctd_amount_from,
    acctd_amount_applied_to::number       as acctd_amount_to,
    acctd_earned_discount_taken::number   as acctd_earned_discount,
    confirmed_flag,
    program_application_id,
    program_id::number                    as program_id,
    program_update_date::timestamp_ntz    as program_updated_at,
    request_id::number                     as request_id,
    ussgl_transaction_code,
    ussgl_transaction_code_context,
    earned_discount_ccid::number         as earned_discount_ccid,
    unearned_discount_ccid::number       as unearned_discount_ccid,
    acctd_unearned_discount_taken::number as acctd_unearned_discount,
    reversal_gl_date::timestamp_ntz       as reversal_gl_date,
    reversal_gl_date_context,
    cash_receipt_history_id::number      as cash_receipt_history_id,
    org_id,
    tax_code,
    cons_inv_id,
    cons_inv_id_to,
    amount_applied_from::number          as amount_applied_from,
    trans_to_receipt_rate::number       as trans_to_receipt_rate,
    rule_set_id::number                  as rule_set_id,
    line_ediscounted::number             as line_ediscounted,
    tax_ediscounted::number              as tax_ediscounted,
    freight_ediscounted::number          as freight_ediscounted,
    charges_ediscounted::number          as charges_ediscounted,
    line_uediscounted::number            as line_uediscounted,
    tax_uediscounted::number             as tax_uediscounted,
    freight_uediscounted::number         as freight_uediscounted,
    charges_uediscounted::number         as charges_uediscounted,
    mrc_amount_applied,
    mrc_amount_applied_from,
    mrc_display,
    mrc_status,
    mrc_payment_schedule_id,
    mrc_cash_receipt_id,
    mrc_gl_posted_date,
    mrc_posting_control_id,
    mrc_acctd_amount_applied_from,
    mrc_acctd_amount_applied_to,
    mrc_acctd_earned_disc_taken,
    mrc_acctd_unearned_disc_taken,
    edisc_tax_acct_rule,
    unedisc_tax_acct_rule,
    link_to_trx_hist_id,
    link_to_customer_trx_id,
    application_ref_type,
    application_ref_id,
    application_ref_num,
    chargeback_customer_trx_id,
    secondary_application_ref_id,
    payment_set_id,
    application_ref_reason,
    customer_reference,
    customer_reason,
    applied_rec_app_id,
    secondary_application_ref_type,
    secondary_application_ref_num,
    event_id::number                      as event_id,
    upgrade_method,
    ax_accounted_flag,
    include_in_accumulation,
    on_acct_cust_id,
    on_acct_cust_site_use_id,
    on_acct_po_num,
    rnum::number                         as rnum
  from source
)

select * from cleaned
