with source as (
  select * from {{ source('ar_raw', 'raw_ra_customer_trx_lines_all') }}
),

cleaned as (
  select
    customer_trx_line_id,
    last_update_date::timestamp_ntz      as last_updated_at,
    last_updated_by,
    creation_date::timestamp_ntz         as created_at,
    created_by,
    last_update_login::number            as last_update_login,
    customer_trx_id,
    line_number,
    set_of_books_id,
    reason_code,
    inventory_item_id::number            as inventory_item_id,
    previous_customer_trx_id,
    previous_customer_trx_line_id,
    quantity_ordered::number             as quantity_ordered,
    quantity_credited::number            as quantity_credited,
    quantity_invoiced::number            as quantity_invoiced,
    unit_standard_price::number          as unit_standard_price,
    unit_selling_price::number           as unit_selling_price,
    sales_order,
    sales_order_revision,
    sales_order_line,
    sales_order_date::timestamp_ntz      as sales_order_date,
    accounting_rule_id::number           as accounting_rule_id,
    accounting_rule_duration::number     as accounting_rule_duration,
    line_type,
    rule_start_date::timestamp_ntz       as rule_start_date,
    initial_customer_trx_line_id,
    interface_line_context,
    sales_order_source,
    taxable_flag,
    extended_amount::number              as extended_amount,
    revenue_amount::number               as revenue_amount,
    autorule_complete_flag,
    link_to_cust_trx_line_id::number     as link_to_cust_trx_line_id,
    tax_precedence,
    tax_rate::number                     as tax_rate,
    item_exception_rate_id,
    tax_exemption_id::number             as tax_exemption_id,
    memo_line_id,
    autorule_duration_processed::number  as autorule_duration_processed,
    uom_code,
    default_ussgl_transaction_code,
    default_ussgl_trx_code_context,
    vat_tax_id::number                   as vat_tax_id,
    autotax,
    last_period_to_credit,
    item_context,
    tax_exempt_flag,
    tax_exempt_number,
    tax_exempt_reason_code,
    tax_vendor_return_code,
    sales_tax_id::number                 as sales_tax_id,
    location_segment_id::number         as location_segment_id,
    movement_id,
    org_id,
    gross_unit_selling_price,
    gross_extended_amount,
    amount_includes_tax_flag,
    taxable_amount::number               as taxable_amount,
    warehouse_id::number                 as warehouse_id,
    translated_description,
    extended_acctd_amount,
    br_ref_customer_trx_id,
    br_ref_payment_schedule_id,
    br_adjustment_id,
    mrc_extended_acctd_amount,
    payment_set_id,
    contract_line_id,
    source_data_key1,
    source_data_key2,
    source_data_key3,
    source_data_key4,
    source_data_key5,
    invoiced_line_acctg_level,
    override_auto_accounting_flag,
    ship_to_customer_id::number         as ship_to_customer_id,
    ship_to_address_id,
    ship_to_site_use_id::number         as ship_to_site_use_id,
    ship_to_contact_id::number          as ship_to_contact_id,
    historical_flag,
    tax_line_id::number                  as tax_line_id,
    line_recoverable::number             as line_recoverable,
    tax_recoverable::number              as tax_recoverable,
    tax_classification_code,
    amount_due_remaining,
    acctd_amount_due_remaining,
    amount_due_original,
    acctd_amount_due_original,
    chrg_amount_remaining::number        as chrg_amount_remaining,
    chrg_acctd_amount_remaining::number as chrg_acctd_amount_remaining,
    frt_adj_remaining::number            as frt_adj_remaining,
    frt_adj_acctd_remaining::number      as frt_adj_acctd_remaining,
    frt_ed_amount::number                as frt_ed_amount,
    frt_ed_acctd_amount::number          as frt_ed_acctd_amount,
    frt_uned_amount::number              as frt_uned_amount,
    frt_uned_acctd_amount::number        as frt_uned_acctd_amount,
    deferral_exclusion_flag,
    rule_end_date,
    payment_trxn_extension_id::number    as payment_trxn_extension_id,
    interest_line_id,
    doc_line_id_int_1,
    doc_line_id_int_2,
    doc_line_id_int_3,
    doc_line_id_int_4,
    doc_line_id_int_5,
    doc_line_id_char_1,
    doc_line_id_char_2,
    doc_line_id_char_3,
    doc_line_id_char_4,
    doc_line_id_char_5,
    tax_calc_acctd_amt,
    rnum::number                         as rnum
  from source
)

select * from cleaned
