with source as (
  select * from {{ source('ar_raw', 'raw_ra_customer_trx_all') }}
),

cleaned as (
  select
    customer_trx_id,
    last_update_date::timestamp_ntz      as last_updated_at,
    last_updated_by,
    creation_date::timestamp_ntz         as created_at,
    created_by,
    last_update_login,
    trx_number,
    cust_trx_type_id,
    trx_date::timestamp_ntz              as trx_date,
    set_of_books_id,
    bill_to_contact_id::number           as bill_to_contact_id,
    batch_id::number                     as batch_id,
    batch_source_id,
    reason_code,
    sold_to_customer_id::number          as sold_to_customer_id,
    sold_to_contact_id,
    sold_to_site_use_id,
    bill_to_customer_id,
    bill_to_site_use_id,
    ship_to_customer_id::number          as ship_to_customer_id,
    ship_to_contact_id::number           as ship_to_contact_id,
    ship_to_site_use_id::number          as ship_to_site_use_id,
    shipment_id,
    remit_to_address_id::number          as remit_to_address_id,
    term_id::number                      as term_id,
    term_due_date::timestamp_ntz         as term_due_date,
    previous_customer_trx_id::number     as previous_customer_trx_id,
    primary_salesrep_id::number          as primary_salesrep_id,
    printing_original_date::timestamp_ntz as printing_original_at,
    printing_last_printed::timestamp_ntz as printing_last_printed_at,
    printing_option,
    printing_count::number               as printing_count,
    printing_pending,
    purchase_order,
    purchase_order_revision,
    purchase_order_date,
    customer_reference,
    customer_reference_date::timestamp_ntz as customer_reference_at,
    comments,
    internal_notes,
    exchange_rate_type,
    exchange_date::timestamp_ntz         as exchange_date,
    exchange_rate::number                as exchange_rate,
    invoice_currency_code,
    initial_customer_trx_id::number      as initial_customer_trx_id,
    agreement_id,
    end_date_commitment::timestamp_ntz    as end_date_commitment,
    start_date_commitment::timestamp_ntz  as start_date_commitment,
    last_printed_sequence_num::number    as last_printed_sequence_num,
    orig_system_batch_name,
    post_request_id,
    finance_charges,
    complete_flag,
    posting_control_id::number           as posting_control_id,
    bill_to_address_id::number           as bill_to_address_id,
    ra_post_loop_number,
    ship_to_address_id::number           as ship_to_address_id,
    credit_method_for_rules,
    credit_method_for_installments,
    receipt_method_id::number            as receipt_method_id,
    related_customer_trx_id::number      as related_customer_trx_id,
    invoicing_rule_id::number            as invoicing_rule_id,
    ship_via,
    ship_date_actual::timestamp_ntz      as ship_date_actual,
    waybill_number,
    fob_point,
    customer_bank_account_id::number     as customer_bank_account_id,
    interface_header_context,
    default_ussgl_trx_code_context,
    default_ussgl_transaction_code,
    recurred_from_trx_number,
    status_trx,
    doc_sequence_id::number              as doc_sequence_id,
    doc_sequence_value::number           as doc_sequence_value,
    paying_customer_id::number           as paying_customer_id,
    paying_site_use_id::number           as paying_site_use_id,
    related_batch_source_id,
    default_tax_exempt_flag,
    created_from,
    org_id,
    edi_processed_flag,
    edi_processed_status,
    mrc_exchange_rate_type,
    mrc_exchange_date,
    mrc_exchange_rate,
    payment_server_order_num,
    approval_code,
    address_verification_code,
    old_trx_number,
    br_amount,
    br_unpaid_flag,
    br_on_hold_flag,
    drawee_id,
    drawee_contact_id,
    drawee_site_use_id,
    remittance_bank_account_id,
    override_remit_account_flag,
    drawee_bank_account_id,
    special_instructions,
    remittance_batch_id,
    prepayment_flag,
    ct_reference,
    contract_id,
    bill_template_id,
    reversed_cash_receipt_id,
    cc_error_code,
    cc_error_text,
    cc_error_flag,
    upgrade_method,
    legal_entity_id,
    remit_bank_acct_use_id,
    payment_trxn_extension_id::number as payment_trxn_extension_id,
    ax_accounted_flag,
    billing_date,
    interest_header_id,
    late_charges_assessed,
    trailer_number,
    rev_rec_application,
    document_type_id,
    document_creation_date,
    src_invoicing_rule_id,
    billing_ext_request,
    rnum::number                        as rnum
  from source
)

select * from cleaned
