with source as (
  select * from {{ source('ont_raw', 'raw_oe_price_adjustments') }}
),

cleaned as (
  select
    price_adjustment_id,
    creation_date::timestamp_ntz         as created_at,
    created_by,
    last_update_date::timestamp_ntz      as last_updated_at,
    last_updated_by,
    last_update_login::number            as last_update_login,
    header_id,
    discount_id,
    discount_line_id,
    automatic_flag,
    percent,
    line_id::number                      as line_id,
    context,
    orig_sys_discount_ref,
    change_sequence,
    list_header_id::number               as list_header_id,
    list_line_id::number                 as list_line_id,
    list_line_type_code,
    modified_from,
    modified_to,
    update_allowed,
    change_reason_code,
    change_reason_text,
    modifier_mechanism_type_code,
    updated_flag,
    applied_flag,
    operand::number                      as operand,
    arithmetic_operator,
    cost_id::number                      as cost_id,
    tax_code,
    tax_exempt_flag,
    tax_exempt_number,
    tax_exempt_reason_code,
    parent_adjustment_id,
    invoiced_flag,
    estimated_flag,
    inc_in_sales_performance,
    split_action_code,
    adjusted_amount::number              as adjusted_amount,
    pricing_phase_id::number             as pricing_phase_id,
    charge_type_code,
    charge_subtype_code,
    range_break_quantity,
    accrual_conversion_rate,
    pricing_group_sequence::number       as pricing_group_sequence,
    accrual_flag,
    list_line_no,
    source_system_code,
    benefit_qty,
    benefit_uom_code,
    print_on_invoice_flag,
    expiration_date,
    rebate_transaction_type_code,
    rebate_transaction_reference,
    rebate_payment_system_code,
    redeemed_date,
    redeemed_flag,
    modifier_level_code,
    price_break_type_code,
    proration_type_code,
    include_on_returns_flag,
    credit_or_charge_flag,
    ac_context,
    operand_per_pqty::number             as operand_per_pqty,
    adjusted_amount_per_pqty::number     as adjusted_amount_per_pqty,
    interco_invoiced_flag,
    invoiced_amount,
    retrobill_request_id,
    tax_rate_id::number                  as tax_rate_id,
    inst_id,
    rebate_type,
    rnum::number                         as rnum
  from source
)

select * from cleaned
