with source as (
  select * from {{ source('ont_raw', 'raw_oe_order_lines_all') }}
),

cleaned as (
  select
    line_id,
    org_id,
    header_id,
    line_type_id,
    line_number,
    ordered_item,
    request_date::timestamp_ntz        as requested_at,
    promise_date::timestamp_ntz        as promised_at,
    schedule_ship_date::timestamp_ntz  as scheduled_ship_at,
    order_quantity_uom,
    pricing_quantity::number           as pricing_quantity,
    pricing_quantity_uom,
    cancelled_quantity::number         as cancelled_quantity,
    shipped_quantity,
    ordered_quantity,
    fulfilled_quantity,
    shipping_quantity,
    shipping_quantity_uom,
    delivery_lead_time,
    tax_exempt_flag,
    tax_exempt_number,
    tax_exempt_reason_code,
    ship_from_org_id,
    ship_to_org_id,
    invoice_to_org_id,
    deliver_to_org_id,
    ship_to_contact_id::number         as ship_to_contact_id,
    deliver_to_contact_id,
    invoice_to_contact_id::number      as invoice_to_contact_id,
    intmed_ship_to_org_id,
    intmed_ship_to_contact_id,
    sold_from_org_id,
    sold_to_org_id,
    cust_po_number,
    ship_tolerance_above,
    ship_tolerance_below,
    demand_bucket_type_code,
    veh_cus_item_cum_key_id,
    rla_schedule_type_code,
    customer_dock_code,
    customer_job,
    customer_production_line,
    cust_model_serial_number,
    project_id,
    task_id,
    inventory_item_id,
    tax_date::timestamp_ntz           as tax_at,
    tax_code,
    tax_rate,
    invoice_interface_status_code,
    demand_class_code,
    price_list_id,
    pricing_date::timestamp_ntz       as pricing_date,
    shipment_number,
    agreement_id,
    shipment_priority_code,
    shipping_method_code,
    freight_carrier_code,
    freight_terms_code,
    fob_point_code,
    tax_point_code,
    payment_term_id,
    invoicing_rule_id,
    accounting_rule_id,
    source_document_type_id,
    orig_sys_document_ref,
    source_document_id,
    orig_sys_line_ref,
    source_document_line_id,
    reference_line_id,
    reference_type,
    reference_header_id,
    item_revision,
    unit_selling_price::number        as unit_selling_price,
    unit_list_price::number           as unit_list_price,
    tax_value::number                 as tax_value,
    context,
    pricing_context,
    industry_context,
    creation_date::timestamp_ntz      as created_at,
    created_by,
    last_update_date::timestamp_ntz   as last_updated_at,
    last_updated_by,
    last_update_login,
    top_model_line_id,
    link_to_line_id,
    component_sequence_id,
    component_code,
    config_display_sequence,
    sort_order,
    item_type_code,
    option_number,
    option_flag,
    dep_plan_required_flag,
    visible_demand_flag,
    line_category_code,
    actual_shipment_date::timestamp_ntz as actual_shipped_at,
    customer_trx_line_id,
    return_context,
    actual_arrival_date,
    ato_line_id,
    auto_selected_quantity,
    component_number,
    earliest_acceptable_date::timestamp_ntz as earliest_acceptable_at,
    latest_acceptable_date::timestamp_ntz   as latest_acceptable_at,
    model_group_number,
    schedule_arrival_date::timestamp_ntz   as schedule_arrival_at,
    ship_model_complete_flag,
    schedule_status_code,
    source_type_code,
    cancelled_flag,
    open_flag,
    booked_flag,
    salesrep_id,
    return_reason_code,
    arrival_set_id,
    ship_set_id::number                as ship_set_id,
    split_from_line_id::number         as split_from_line_id,
    cust_production_seq_num,
    authorized_to_ship_flag,
    over_ship_reason_code,
    over_ship_resolved_flag,
    ordered_item_id,
    item_identifier_type,
    configuration_id,
    commitment_id,
    shipping_interfaced_flag,
    credit_invoice_line_id,
    first_ack_code,
    first_ack_date,
    last_ack_code,
    last_ack_date,
    planning_priority,
    order_source_id,
    orig_sys_shipment_ref,
    change_sequence,
    drop_ship_flag,
    customer_line_number,
    customer_shipment_number,
    customer_item_net_price,
    TRY_TO_NUMBER(TO_VARCHAR(customer_payment_term_id)) AS customer_payment_term_id,
    fulfilled_flag,
    end_item_unit_number,
    config_header_id,
    config_rev_nbr,
    mfg_component_sequence_id,
    invoiced_quantity,
    reference_customer_trx_line_id,
    split_by,
    line_set_id::number as line_set_id,
    service_txn_reason_code,
    service_txn_comments,
    service_duration,
    service_start_date,
    service_end_date,
    service_coterminate_flag,
    unit_list_percent,
    unit_selling_percent::number         as unit_selling_percent,
    unit_percent_base_price,
    service_number,
    service_period,
    shippable_flag,
    model_remnant_flag,
    re_source_flag,
    flow_status_code,
    tp_context,
    fulfillment_method_code,
    marketing_source_code_id,
    service_reference_type_code,
    service_reference_line_id,
    service_reference_system_id,
    calculate_price_flag,
    upgraded_flag,
    revenue_amount,
    fulfillment_date::timestamp_ntz    as fulfillment_date,
    preferred_grade,
    ordered_quantity2::number           as ordered_quantity2,
    ordered_quantity_uom2,
    shipping_quantity2::number          as shipping_quantity2,
    cancelled_quantity2,
    shipped_quantity2::number           as shipped_quantity2,
    shipping_quantity_uom2,
    fulfilled_quantity2,
    mfg_lead_time::number               as mfg_lead_time,
    subinventory,
    unit_list_price_per_pqty::number    as unit_list_price_per_pqty,
    unit_selling_price_per_pqty::number as unit_selling_price_per_pqty,
    price_request_code,
    original_inventory_item_id,
    original_ordered_item_id,
    original_ordered_item,
    original_item_identifier_type,
    item_substitution_type_code,
    override_atp_date_code,
    late_demand_penalty_factor,
    accounting_rule_duration,
    user_item_description,
    unit_cost::number                    as unit_cost,
    item_relationship_type,
    blanket_line_number,
    blanket_number,
    blanket_version_number,
    sales_document_type_code,
    firm_demand_flag,
    earliest_ship_date,
    transaction_phase_code,
    source_document_version_number,
    payment_type_code,
    end_customer_id,
    end_customer_contact_id,
    end_customer_site_use_id,
    retrobill_request_id,
    original_list_price,
    service_credit_eligible_code,
    order_firmed_date,
    actual_fulfillment_date::timestamp_ntz as actual_fulfillment_at,
    charge_periodicity_code,
    contingency_id,
    revrec_event_code,
    revrec_expiration_days,
    accepted_quantity,
    accepted_by,
    revrec_comments,
    revrec_reference_document,
    revrec_signature,
    revrec_signature_date,
    revrec_implicit_flag,
    bypass_sch_flag,
    pre_exploded_flag,
    inst_id,
    tax_line_value,
    service_bill_profile_id,
    service_cov_template_id,
    service_subs_template_id,
    service_bill_option_code,
    service_first_period_amount,
    service_first_period_enddate,
    subscription_enable_flag,
    fulfillment_base,
    container_number,
    equipment_id,
    require_billing_validation,
    billing_plan_header_id,
    source_order_line_id,
    vrm_last_update_date,
    rnum::number                         as rnum
  from source
)

select * from cleaned
