with source as (
  select * from {{ source('ont_raw', 'raw_oe_order_headers_all') }}
),

cleaned as (
  select
    header_id,
    org_id,
    order_type_id,
    order_number,
    version_number,
    expiration_date,
    order_source_id::number            as order_source_id,
    source_document_type_id::number   as source_document_type_id,
    orig_sys_document_ref,
    source_document_id::number        as source_document_id,
    ordered_date::timestamp_ntz       as ordered_at,
    request_date::timestamp_ntz       as requested_at,
    pricing_date::timestamp_ntz       as pricing_at,
    shipment_priority_code,
    demand_class_code,
    price_list_id::number             as price_list_id,
    tax_exempt_flag,
    tax_exempt_number,
    tax_exempt_reason_code,
    conversion_rate::number           as conversion_rate,
    conversion_type_code,
    conversion_rate_date,
    partial_shipments_allowed,
    ship_tolerance_above,
    ship_tolerance_below,
    transactional_curr_code,
    agreement_id,
    tax_point_code,
    cust_po_number,
    invoicing_rule_id::number         as invoicing_rule_id,
    accounting_rule_id::number        as accounting_rule_id,
    payment_term_id,
    shipping_method_code,
    freight_carrier_code,
    fob_point_code,
    freight_terms_code,
    sold_from_org_id,
    sold_to_org_id,
    ship_from_org_id::number          as ship_from_org_id,
    ship_to_org_id::number            as ship_to_org_id,
    invoice_to_org_id::number         as invoice_to_org_id,
    deliver_to_org_id,
    sold_to_contact_id::number        as sold_to_contact_id,
    ship_to_contact_id::number        as ship_to_contact_id,
    invoice_to_contact_id::number     as invoice_to_contact_id,
    deliver_to_contact_id,
    creation_date::timestamp_ntz      as created_at,
    created_by,
    last_updated_by,
    last_update_date::timestamp_ntz   as last_updated_at,
    last_update_login,
    context,
    cancelled_flag::boolean           as cancelled_flag,
    open_flag::boolean                as open_flag,
    booked_flag::boolean              as booked_flag,
    salesrep_id,
    return_reason_code,
    order_date_type_code,
    earliest_schedule_limit,
    latest_schedule_limit,
    payment_type_code,
    payment_amount::number            as payment_amount,
    check_number,
    sales_channel_code,
    first_ack_code,
    first_ack_date,
    last_ack_code,
    last_ack_date,
    order_category_code,
    change_sequence,
    drop_ship_flag,
    customer_payment_term_id,
    tp_context,
    flow_status_code,
    marketing_source_code_id::number  as marketing_source_code_id,
    credit_card_approval_date,
    upgraded_flag,
    customer_preference_set_code,
    booked_date::timestamp_ntz        as booked_at,
    price_request_code,
    batch_id,
    accounting_rule_duration,
    blanket_number,
    sales_document_type_code,
    sold_to_phone_id,
    fulfillment_set_name,
    line_set_name,
    default_fulfillment_set,
    transaction_phase_code,
    sales_document_name,
    quote_number,
    quote_date,
    user_status_code,
    draft_submitted_flag,
    source_document_version_number,
    sold_to_site_use_id::number      as sold_to_site_use_id,
    supplier_signature_date,
    customer_signature_date::timestamp_ntz as customer_signed_at,
    end_customer_id,
    end_customer_contact_id,
    end_customer_site_use_id,
    order_firmed_date,
    inst_id,
    csr_user_id,
    cancel_unshipped_lines,
    rnum::number                       as rnum
  from source
)

select * from cleaned

