with source as (
  select * from {{ source('wsh_raw', 'raw_wsh_picking_batches') }}
),

cleaned as (
  select
    batch_id,
    name,
    backorders_only_flag,
    document_set_id::number              as document_set_id,
    existing_rsvs_only_flag,
    shipment_priority_code,
    ship_method_code,
    carrier_id,
    customer_id::number                 as customer_id,
    ship_to_location_id,
    order_header_id::number             as order_header_id,
    order_line_id,
    ship_set_number,
    inventory_item_id,
    order_type_id::number               as order_type_id,
    from_requested_date,
    to_requested_date::timestamp_ntz    as to_requested_at,
    from_scheduled_ship_date::timestamp_ntz as from_scheduled_ship_at,
    to_scheduled_ship_date::timestamp_ntz   as to_scheduled_ship_at,
    subinventory,
    ship_from_location_id::number       as ship_from_location_id,
    organization_id::number             as organization_id,
    default_stage_subinventory,
    default_stage_locator_id,
    pick_from_subinventory,
    pick_from_locator_id,
    autodetail_pr_flag,
    auto_pick_confirm_flag,
    trip_id,
    trip_stop_id,
    delivery_id,
    delivery_detail_id,
    pick_grouping_rule_id,
    pick_sequence_rule_id,
    partial_allowed_flag,
    include_planned_lines,
    autocreate_delivery_flag,
    creation_date::timestamp_ntz        as created_at,
    created_by,
    last_update_date::timestamp_ntz     as last_updated_at,
    last_updated_by,
    last_update_login::number           as last_update_login,
    project_id,
    task_id,
    auto_send_doc_flag,
    non_picking_flag,
    ship_confirm_rule_id,
    autopack_flag,
    autopack_level,
    delivery_name_lo,
    delivery_name_hi,
    bol_number_lo,
    bol_number_hi,
    intmed_ship_to_loc_id,
    pooled_ship_to_loc_id,
    fob_code,
    freight_terms_code,
    pickup_date_lo,
    pickup_date_hi,
    dropoff_date_lo,
    dropoff_date_hi,
    planned_flag,
    selected_batch_id,
    task_planning_flag,
    append_flag,
    region_id,
    zone_id,
    category_id,
    category_set_id,
    ac_delivery_criteria,
    rel_subinventory,
    ship_set_smc_flag,
    task_priority,
    allocation_method,
    crossdock_criteria_id,
    actual_departure_date,
    dynamic_replenishment_flag,
    client_id,
    org_id,
    rnum::number                        as rnum
  from source
)

select * from cleaned
